config/routes.rb
TodoApp::Application.routes.draw do

  resources :projects do
    resources :items, only: [:index]
  end

  resources :items do
    collection do
      put "batch_update"
    end
  end

  resources :teams do
    resources :projects, only: [:new]
  end

  resources :users

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :completed, :description, :project_id, :title

  validates :completed, inclusion: { in: [true, false] }
  # validates :description ???
  validates :project_id, presence: true
  validates :title, presence: true

  belongs_to :project, class_name: "Project", primary_key: :id,
  foreign_key: :project_id

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :team_id

  # validates :description, presence: true # ???
  validates :title, presence: true
  validates :team_id, presence: true

  has_many :items, class_name: "Item", primary_key: :id,
  foreign_key: :project_id, dependent: :destroy

  belongs_to :team, class_name: "Team", primary_key: :id,
  foreign_key: :team_id

end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name

  has_many :projects, class_name: "Project", primary_key: :id,
  foreign_key: :team_id, dependent: :destroy

  has_many :team_memberships, class_name: "TeamMembership", primary_key: :id,
  foreign_key: :team_id, dependent: :destroy

  has_many :members, through: :team_memberships, source: :user, inverse_of: :teams
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  attr_accessible :team_id, :user_id

  validates :team_id, presence: true
  validates :user_id, presence: true

  belongs_to :team, class_name: "Team", primary_key: :id,
  foreign_key: :team_id

  belongs_to :user, class_name: "User", primary_key: :id,
  foreign_key: :user_id


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :team_ids

  validates :name, presence: true

  has_many :team_memberships, class_name: "TeamMembership", primary_key: :id,
  foreign_key: :user_id, dependent: :destroy

  has_many :teams, through: :team_memberships, source: :team, inverse_of: :members

  def team_ids=(ids)
    self.teams = ids.map { |id| Team.find(id) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @projects = Project.all
    @item = Item.new
    render :new
  end

  def show
    @item = Item.find(params[:id])
    render :show
  end

  def create
    @item = Item.new(params[:item])
    @item.completed = false

    if @item.save
      redirect_to project_url(@item.project_id)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @item.errors.full_messages
      @projects = Project.all
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @projects = Project.all
    render :edit
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to project_url(@item.project_id)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @item.errors.full_messages
      @projects = Project.all
      render :new
    end
  end

  def index
    @project_id = params[:project_id]
    @items = Item.where(project_id: @project_id)

    render :index
  end

  def batch_update
    # Separate ids for whom completed is to be set to true
    true_ids = []
    false_ids = []
    params[:items].each do |key, value|
      if value[:completed] == "true"
        true_ids << key
      else
        false_ids << key
      end
    end

    # Use one query to set all true_ids to true
    Item.where(id: true_ids).update_all(completed: true)
    Item.where(id: false_ids).update_all(completed: false)

    # get one of the Items and find its project id to send us there
    project_id = Item.find(params[:items].keys.first.to_i).project_id
    redirect_to project_url(project_id)

  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    render :index
  end

  def new
    @team_id = params[:team_id]
    @teams = Team.all
    render :new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      redirect_to projects_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @project.errors.full_messages
    end
  end

  def show
    @project = Project.find(params[:id])
    render :show
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.includes(:projects).find(params[:id])
  end

  def new
    @team = Team.new
    render :new
  end

  def create
    @team = Team.new(params[:team])

    if @team.save
      redirect_to projects_url # teams_url?
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @team.errors.full_messages
      render :new
    end
  end

  def index
    @teams = Team.all
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @teams = Team.all
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to projects_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += @user.errors.full_messages
      @teams = Team.all
      render :new
    end

  end

  def show
    @user = User.includes(:teams).find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<form action="<%= url %>", method="post">
  <% if method == "update" %>
    <input type="hidden" name="_method" value="put">
  <% end %>

  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label>
    Item title
    <input type="text" name="item[title]" value="<%= @item.title %>">
  </label>

  <label>
    Item description
    <textarea name="item[description]"><%= @item.description %></textarea>
  </label>

  <label>
    Item project
    <select name="item[project_id]">
      <% @projects.each do |project| %>
        <option value="<%= project.id %>"><%= project.title %></option>
      <% end %>
    </select>
  </label>

  <% if method == "update" %>
  <label>
    Item completed
    <input type="checkbox" name="item[completed]" value="true">
  </label>
  <% end %>

  <input type="submit" value="Create item!">

</form>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render "form", url: item_url(@item), method: "update" %>

app/views/items/index.html.erb
<h1>Items</h1>
<br>

<% @items.each do |item| %>
  <%= link_to item.title, item_url(item) %>
  <br>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render "form", url: items_url, method: "post" %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<br>
<p><%= @item.description %></p>
<br>

<p>This item has <%= !@item.completed ? "not" : "" %> been completed.</p>
<br>
<%= link_to "Edit this item", edit_item_url(@item) %>
<br>
<%= link_to @item.project.title, project_url(@item.project_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to "All Projects", projects_url %>
  <%= link_to "Create New Project", new_project_url %>
  <%= link_to "All Teams", teams_url %>
  <%= link_to "Create New Team", new_team_url %>
  <br>

<%= yield %>

<% flash.now[:errors].try(:each) do |error| %>
  <%= error%>
<% end %>
</body>
</html>

app/views/projects/index.html.erb
<h1>Your Projects</h1>
<% @projects.each do |project| %>
  <%= link_to project.title, project_url(project) %>
  <br>
<% end %>

app/views/projects/new.html.erb
<h1>Create a Project</h1>
<form action="<%= projects_url %>" method="post">
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">

  <label>
    Project Title
    <input type="text" name="project[title]">
  </label>
  <br>

  <label>
    Project Description
    <textarea name="project[description]"></textarea>
  </label>
  <br>

  <label>
    Team
    <select name="project[team_id]">
      <% @teams.each do |team| %>
        <option value="<%= team.id %>" selected="<%= @team_id == team.id ?
           "selected" : "" %>"><%= team.name %></option>
      <% end %>
    </select>
  </label>
  <br>

  <input type="submit" value="Create Project!">
</form>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<br>

<p>This is a <%= @project.team.name %> project.</p>

<br>
<%= @project.description %>
<br>

<form action="<%= batch_update_items_url %>" method="post">
  <input  type="hidden" name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="put">

  <% @project.items.each do |item| %>
    <br>
    <%= link_to item.title, item_url(item) %>


    <input type="hidden" name="items[<%= item.id %>][completed]" value="false">
    <br>
    <label>
      Item completed?
      <input type="checkbox" name="items[<%= item.id %>][completed]" value="true"
      <%= item.completed ? "checked" : "" %>>
    </label>
    <br>

  <% end %>

  <input type="submit" value="Update items">
</form>
<br>

<br>
<%= link_to "Add new item", new_item_url %>
<br>
<%= link_to @project.team.name, team_url(@project.team_id) %>

app/views/users/new.html.erb
<h1>New User</h1>
<form action="<%= users_url %>" method="post">

  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label>
    Name
    <input type="text" name="user[name]" value="<%= @user.name %>">
  </label>

  <% @teams.each do |team| %>
    <label>
      <%= team.name %>
      <input type="checkbox" name="user[team_ids][]" value="<%= team.id %>">
    </label>
  <% end %>

  <input type="submit" value="Create user!">


</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<br>

<h4>Teams</h4>
<br>

<% @user.teams.each do |team| %>
  <%= link_to team.name, team_url(team) %>
  <br>
<% end %>